repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.92.0
  hooks:
  - id: terraform_fmt
    args:
    - --args=-diff
    - --args=-write=false
  - id: terraform_validate
  - id: terraform_tflint
    args:
    - '--args=--only=terraform_deprecated_interpolation'
    - '--args=--only=terraform_deprecated_index'
  - id: terraform_docs
    args:
    - --hook-config=--path-to-file=README.md
    - --hook-config=--add-to-existing-file=true
    - --hook-config=--create-file-if-not-exist=true
